version: "3.9"

services:
  app:
    build:
      context: "./app"
    env_file: .env
    volumes:
      - ./app/:/usr/app/
    depends_on:
      - database
    ports:
      - "8082:8000"
    networks:
      - production-network
    expose:
     - 8000
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: v25xhycLlRY3sV7Z
      MYSQL_DATABASE: "exercise"
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - production-network
    ports:
      - "3306:3306"
    expose:
      - 3306 
networks:
  production-network:
    driver: bridge
